# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 04:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='BG')),
                ('timestamp', models.DateTimeField(verbose_name='date submitted')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date submitted')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=4)),
                ('is_prebolus', models.BooleanField(verbose_name='Prebolus for meal')),
            ],
        ),
        migrations.CreateModel(
            name='Extended_Bolus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date submitted')),
                ('duration', models.PositiveIntegerField()),
                ('percent_now', models.DecimalField(decimal_places=2, max_digits=2)),
                ('percent_later', models.DecimalField(decimal_places=2, max_digits=2)),
                ('assoc_dose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.Dose')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date submitted')),
                ('time_of_day', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('N', 'Bedtime'), ('S', 'Snack'), (None, 'No meal set')], max_length=1)),
                ('carbs', models.PositiveIntegerField()),
                ('carb_ratio', models.DecimalField(decimal_places=2, max_digits=2)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date submitted')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='assoc_treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.Treatment'),
        ),
        migrations.AddField(
            model_name='dose',
            name='assoc_treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.Treatment', verbose_name='Associated treatment'),
        ),
        migrations.AddField(
            model_name='bg',
            name='assoc_treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.Treatment', verbose_name='Associated treatment'),
        ),
    ]
